name: release
on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Which number to increment in the semantic versioning.
          Set 'major', 'minor' or 'patch'.
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Wait Tests
        id: test_result
        uses: Sibz/await-status-action@v1.0.2
        with:
          contexts: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Test Result
        if: steps.test_result.outputs.result != 'success'
        run: |
          echo "failed ${{ steps.test_result.outputs.failedCheckNames }}"
          echo "status ${{ steps.test_result.outputs.failedCheckStates }}"
          exit 1
      - name: Install Dependency (Ubuntu)
        run: |
          sudo apt update
          sudo apt install -y libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
      - name: Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump-up Semantic Version
        uses: kyoh86/git-vertag-action@v1
        with:
          method: "${{ github.event.inputs.method }}"
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
