name: test
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
      
jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        go: ['1.16.x', '1.17.x']
    name: Test with Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Install Dependency (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          sudo apt update
          sudo apt install -y libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
      - name: Xvfb
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test -race ./...
  test-status:
    name: Test status
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1.1.6
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
